### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dwsupplee**
Let's see where this goes

### CODE REVIEW

**Comment by dwsupplee** [comment]
This is the least polite acceptance of a pull request I have ever seen. It's been minutes I've been waiting now. MINUTES.

**Comment by stephenplusplus** [comment]
I'm sorry, sir. Thank you for sending this!

**Comment by stephenplusplus** [comment]
Asshole.

**Comment by ruyadorno** [comment]
lol

**Pull request merged**
