### PR TITLE
I applaud this bringing together of a community of

### PR DESCRIPTION
**Pull request by daspecster**
like minded people. :metal:

### CODE REVIEW

**Comment by fcanas** [comment]
This is amazing! 

Makes me wish I'd thought of it, but really shows the power of having a lot of people with different perspectives looking at a problem.

:clap:

**Comment by stephenplusplus** [comment]
Speechless.

**Comment by stephenplusplus** [comment]
@fcanas want the honors of hitting the green button? Thanks for sharing my vision for this repo. Welcome to the polite team!

**Comment by fcanas** [comment]
I am honored. Thank you @stephenplusplus

**Comment by daspecster** [comment]
:+1:

**Pull request merged**
