### PR TITLE
Better README title

### PR DESCRIPTION
**Pull request by ruyadorno**
reference

### CODE REVIEW

**Comment by stephenplusplus** [comment]
I would love to merge this PR, but unfortunately, I've created a merge conflict after another merge. I want you to rest assured I do accept it, I just can't merge it.

**Comment by samccone** [comment]
we can merge it

**Comment by samccone** [comment]
just merge it will the diff marks in

**Comment by stephenplusplus** [comment]
Yes, sir!

**Comment by ruyadorno** [comment]
lol

**Comment by ruyadorno** [comment]
now that's the face of chaos!

**Comment by samccone** [comment]
:finnadie:

**Pull request merged**
